name: Deploy to Trigger.dev (self-hosted)

# Requires manually calling the workflow from a branch / commit to deploy to staging
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      # docker setup - part 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker setup - part 2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_DEV_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          # required when self-hosting
          TRIGGER_API_URL: ${{ secrets.TRIGGER_API_URL }}
        # deploy with additional flags
        run: |
          npx trigger.dev@latest deploy --env staging --self-hosted --push
